### ISSUE TITLE
Individual vertical scrolling for all tabs required.

### ISSUE THREAD

**Issue by Feathergunner** [lumen-org/lumen#76]
The Schema-tab and the Specification-tab have no vertical scrollbar, even if the number of parameters is very large, such that not all of them can be displayed at once.
Therefore, in some cases the user can not drag&drop parameters into the desired location, because a parameter and its target slot might not be viewable at once.

**Comment by Feathergunner** [comment]
The vertical scrollbar for the Schema-tab disappeared sometimes since this was fixed :(
Current state of lumen:
![new_noscrollbar](https://user-images.githubusercontent.com/3929002/75024393-98e38b00-5499-11ea-85df-be04bb295eff.png)

Same model, but displayed with lumen.css from #85 
![old_scrollbar](https://user-images.githubusercontent.com/3929002/75024402-9d0fa880-5499-11ea-9818-c4fc64c76838.png)

**Comment by nandaloo** [comment]
is it fixed by this: https://github.com/lumen-org/lumen/issues/83#issuecomment-610651161?
I manually extracted the changes from here again: https://github.com/lumen-org/lumen/pull/85/files
