### ISSUE TITLE
Color Scheme breaks sometimes

### ISSUE THREAD

**Issue by Feathergunner** [lumen-org/lumen#83]
Sometimes the color scheme is strange. In one occasion, setting a color based on a (discrete) variable with values within [0,5] uses a colormap that ranges from -6 to 6 which results in badly readable plots
![bug_report_lumen](https://user-images.githubusercontent.com/3929002/66819515-68b23b80-ef3f-11e9-83e0-c017335e2b02.png)

**Comment by Feathergunner** [comment]
ideas:
- chose colorscheme to ignore outliers
- chose non-linear color scheme such that 'each bin of the color scheme has equal amount of points'

**Comment by Feathergunner** [comment]
Update: I found another case where the color scheme changes. See attached screenshots.
1) Between the two screenshots, I only de-checked the box for data-points in the Specification tab. Note that while the displayed color-scheme of the legend on the right stays the same, the actual used color scheme in the plot seems to change from "diverging_Enum" (greens) to "sequential_Enum" (blues).
2) Also the same bug as above happend again: the variable "educ" only takes values from the set {0,1,2,3,4}. However, the colorscheme is scaled to the interval (-4.4 , 4.4).
![lumen_bug_colors_1](https://user-images.githubusercontent.com/3929002/78169876-5fb41880-7452-11ea-8548-762d2e6c79b3.png)
![lumen_bug_colors_2](https://user-images.githubusercontent.com/3929002/78169880-62af0900-7452-11ea-8c56-edc0754241c8.png)

**Comment by nandaloo** [comment]
Does [](https://github.com/lumen-org/lumen/tree/issue83) fix it?
