### ISSUE TITLE
Frontend sends endless stream of queries

### ISSUE THREAD

**Issue by Feathergunner** [lumen-org/lumen#87]
The backend shows a new message

> received QUERY:{'SHOW': 'MODELS'}

every second or so. This seems to block/overwrite other queries sometimes (?)
This issue appeared after pulling the newest changes on master from 21st and 22nd October.

**Comment by nandaloo** [comment]
I did not confirm it again, but I am pretty sure this is not new behavior. The front end pulls every second or so for new models in the backend.

**Comment by Feathergunner** [comment]
Okay so maybe only the logging behavior changed? At least I have never seen this before the update.
In this case, I think the logging should be adjusted, because these messages make it difficult to track the important logging messages.
